#!/usr/bin/env python3
"""
This program to delete multiple project from Atlassian jira cloud 
Author: nehrusani@gmail.com
"""

import json
import requests
from  requests.auth import HTTPBasicAuth

baseurl = "https://abc.atlassian.net/rest/api/3/project/"
username = 'username@test.com'

"""
Password is not actually a password rather a token created in jira cloud for api access
"""
password = '*************'

"""
Update file where you have put your reuqired to delete project
"""
filepath = "/test/projectlist2delete.txt"


with open(filepath, 'r') as f:
        read_line = f.readlines()
        reading =  list(map(lambda x:x.strip(),read_line))
		
        auth = HTTPBasicAuth(username, password)
        headers = { "Accept": "application/json" }
        connect = requests.request("GET", url, headers=headers, auth=auth, timeout=100000)
        josn_check = json.loads(connect.text)
		
        for second in josn_check:
                for read_json_each in reading:
                        if (second['key']) == read_json_each:                        
                                url_appendkey = (baseurl + second['key'])
                                print("Going to delete", url_appendkey)                                                             
                                connect2 = requests.request("DELETE", url_appendkey,  headers=headers, auth=auth)
                                print(connect2)
